Algoritmo "Calculo de Salário"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2022
Var
sal, horas, ht: real

Inicio
Escreva("Digite seu salário: ")
Leia(sal)
Escreva("Digite as horas trabalhadas: ")
Leia(horas)
           ht <- (sal / horas)
Escreva("Sua hora de trabalho vale: ", ht:5:2)


Fimalgoritmo