Algoritmo "Conversor de Moeda"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/03/2022
Var
vl_dolar, vl_reais: real


Inicio
Escreva ( "Qual sua merreca em Reais ? " )
leia (vl_reais)
vl_dolar <- vl_reais/ 5.08
Escreva ( " Achou que era merreca ? Merreca são seus: ", vl_dolar:5:2 , " doláres!!!" )




Fimalgoritmo