Algoritmo "Imposto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/04/2022
Var
preco, imposto: real


Inicio
Escreva("Qual o preço do produto?")
Leia (preco)
imposto <- preco * 60/100
Escreva ("O imposto será de R$", imposto)





Fimalgoritmo